notes/urls.py
# vi notes/urls.py

# Определение схемы URL для приложения notes.
from django.urls import path
from . import views

app_name = 'notes'
urlpatterns = [
    path('', views.index, name='index'),
    path('categories/', views.categories, name='categories'),
    path('categories/<int:category_id>/', views.category, name='category'),
    path('new_category/', views.new_category, name='new_category'),
    path('new_note/<int:category_id>/', views.new_note, name='new_note'),
    path('edit_note/<int:note_id>/', views.edit_note, name='edit_note'),
]

notes_project/urls.py
# vi notes_project/urls.py

# Определение схемы URL для проекта notes_project.
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
    path('users/', include('users.urls')),
]

users/urls.py
# vi users/urls.py

# Определение схемы URL для приложения users.
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', views.signup, name='signup'),
]

notes/models.py
# vi notes/models.py

from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    # Категория, хранящая заметки.
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural='categories'

    def __str__(self):
        # Возврат строкового представления модели.
        return self.text

class Note(models.Model):
    # Заметка, оставленная пользователем в выбранной категории.
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Возврат строкового представления модели.
        return f'{self.text[:50]}...'

users/models.py
from django.db import models

# Create your models here.

notes/forms.py
# vi notes/forms.py

from django import forms
from .models import Category, Note

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['text']
        labels = {'text': ''}

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['text']
        labels = {'text': 'Note:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

notes/views.py
# vi notes/views.py

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Category, Note
from .forms import CategoryForm, NoteForm

def index(request):
    # Домашняя страница приложения notes.
    return render(request, 'notes/index.html')

@login_required
def categories(request):
    # Вывод списка категорий.
    categories = Category.objects.filter(owner=request.user).order_by('date_added')
    context = {'categories': categories}
    return render(request, 'notes/categories.html', context)

@login_required
def category(request, category_id):
    # Вывод выбранной категории и всех хранящихся в ней заметок.
    category = get_object_or_404(Category, id=category_id)
    # Проверка того, что данная категория принадлежит текущему пользователю.
    if category.owner != request.user:
        raise Http404
    notes = category.note_set.order_by('-date_added')
    context = {'category': category, 'notes': notes}
    return render(request, 'notes/category.html', context)

@login_required
def new_category(request):
    # Добавление новой категории.
    if request.method != 'POST':
        # Данные не отправлены; создание пустой формы.
        form = CategoryForm()
    else:
        # Отправка данных POST; обработка данных.
        form = CategoryForm(data=request.POST)
        if form.is_valid():
            new_category = form.save(commit=False)
            new_category.owner = request.user
            new_category.save()
            return redirect('notes:categories')
    # Вывод пустой или недействительной формы.
    context={'form': form}
    return render(request, 'notes/new_category.html', context)

@login_required
def new_note(request, category_id):
    # Добавление новой заметки в выбранную категорию.
    category = Category.objects.get(id=category_id)
    if request.method != 'POST':
        # Данные не отправлены; создание пустой формы.
        form = NoteForm()
    else:
        # Отправка данных POST; обработка данных.
        form = NoteForm(data=request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.category = category
            new_note.save()
            return redirect('notes:category', category_id=category_id)
    # Вывод пустой или недействительной формы.
    context={'category': category, 'form': form}
    return render(request, 'notes/new_note.html', context)

@login_required
def edit_note(request, note_id):
    # Редактирование существующей заметки.
    note = Note.objects.get(id=note_id)
    category = note.category
    if category.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Исходный запрос; заполнение формы данными из текущей заметки.
        form = NoteForm(instance=note)
    else:
        # Отправка данных POST; обработка данных.
        form = NoteForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('notes:category', category_id=category.id)
    context = {'note': note, 'category': category, 'form': form}
    return render(request, 'notes/edit_note.html', context)

users/views.py
# vi users/views.py

from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    # Регистрация нового пользователя.
    if request.method != 'POST':
        # Вывод пустой формы для регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа в учетную запись и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('notes:index')
    # Вывод пустой или недействительной формы.
    context = {'form': form}
    return render(request, 'registration/signup.html', context)

notes/templates/notes/base.html
<!-- vi notes/templates/notes/base.html -->

<p>
  <a href="{% url 'notes:index' %}">Notes Project</a> -
  <a href="{% url 'notes:categories' %}">Categories</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }} -
    <a href="{% url 'users:logout' %}">Sign out</a>
  {% else %}
    <a href="{% url 'users:login' %}">Sign in</a> -
    <a href="{% url 'users:signup' %}">Sign up</a>
  {% endif %}
</p>

{% block content %}{% endblock content %}

notes/templates/notes/categories.html
<!-- vi notes/templates/notes/categories.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>Categories:</p>
  <ul>
    {% for category in categories %}
      <li>
        <a href="{% url 'notes:category' category.id %}">{{ category }}</a>
      </li>
    {% empty %}
      <li>No categories have been added yet.</li>
    {% endfor %}
  </ul>
  <a href="{% url 'notes:new_category' %}">Add new category</a>
{% endblock content %}

notes/templates/notes/category.html
<!-- vi notes/templates/notes/category.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>Category: {{ category }}</p>
  <p>Notes:</p>
  <p>
    <a href="{% url 'notes:new_note' category.id %}">Add a new note</a>
  </p>
  <ul>
  {% for note in notes %}
    <li>
      <p>{{ note.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ note.text|linebreaks }}</p>
      <p>
        <a href="{% url 'notes:edit_note' note.id %}">Edit note</a>
      </p>
    </li>
  {% empty %}
    <li>There are no notes for this category yet.</li>
  {% endfor %}
  </ul>
{% endblock content %}

notes/templates/notes/edit_note.html
<!-- vi notes/templates/notes/edit_note.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>Category: <a href="{% url 'notes:category' category.id %}">{{ category }}</a></p>
  <p>Edit note:</p>
  <form action="{% url 'notes:edit_note' note.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
  </form>
{% endblock content %}

notes/templates/notes/index.html
<!-- vi notes/templates/notes/index.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>The "Notes" application allows users to leave notes in the created categories.</p>
{% endblock content %}

notes/templates/notes/new_category.html
<!-- vi notes/templates/notes/new_category.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>Add new category:</p>
  <form action="{% url 'notes:new_category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add category</button>
  </form>
{% endblock content %}

notes/templates/notes/new_note.html
<!-- vi notes/templates/notes/new_note.html -->

{% extends "notes/base.html" %}

{% block content %}
  <p>Category: <a href="{% url 'notes:category' category.id %}">{{ category }}</a></p>
  <p>Add a new note:</p>
  <form action="{% url 'notes:new_note' category.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add note</button>
  </form>
{% endblock content %}